name: Check pull request

on:
  pull_request

permissions:
  contents: write
  
jobs:
  check:
    runs-on: ubuntu-latest
    name: Check pull request
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 17

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: v0.18.0

#      - name: detekt
#        run: ./gradlew detekt
#
#      - name: Run reviewdog for Detekt
#        env:
#          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEW_DOG }}
#        run: |
#          find . -regex '^.*/build/reports/detekt/detekt.sarif' -type f | while read file_path; do
#           cat "$file_path" | reviewdog -reporter=github-pr-review -f=sarif -level=info
#          done

      - name: ktlint
        run: ./gradlew ktlintCheck

      - name: Run reviewdog for Ktlint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEW_DOG }}
        run: |
          find . -regex '^.*/build/reports/ktlint/ktlintMainSourceSetCheck/ktlintMainSourceSetCheck.sarif' -type f | while read file_path; do
           cat "$file_path" | reviewdog -reporter=github-pr-review -f=sarif -level=info
          done